name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Memaksa penggunaan Node 24 agar warning hilang
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: baktiprasisto
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Output Branch
        # Update ke v4 yang lebih baru dan stabil
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
